### ISSUE TITLE
Correct package versions?

### ISSUE THREAD

**Issue by m-erdemm** [bpriviere/glas#1]
Hi,
Thank you for your amazing work. I've read your paper and it is really enlightening.
I would like to replicate your results and possibly contribute more on it on my research.
It has been 7 months since the last commit to this project. Are you planning to commit environment.yml file for required packages and their correct versions? At this point,  trial-and-error looks like the only way we have. That would be really appreciated, if you at least give us the correct versions. 
Any answer yes/no could be time saving for anyone who is interested with this work.

Thank you

**Comment by bpriviere** [comment]
Hello, 
Thank you for your interest in our work and for pointing this out. Unfortunately, I don't have access to the environment file during the holidays, I will check in the new year, and get back to you. Happy to keep talking if anything else is a concern. 
Best,
Ben

**Comment by bpriviere** [comment]
Packages have been added in "code/environment.yml", please let me know if there are any further issues.

**Comment by m-erdemm** [comment]
Thank you
